[package]
name = "parm-incremental-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parm-ast = { path = "../parm-ast" }
parm-common = { path = "../parm-common" }