[workspace]
members = [
    "parmesan-ast",
    "parmesan-dev-macros",
    "parmesan-common",
    "parmesan-compiler",
    "alfredo"
, "parmesan-ir", "parmesan-typechecker",  "parmesan-incremental-parser"]
resolver = "2"
