[workspace]
members = [
    "crates/something-frontend",
    "crates/something-dev-tools",
    "crates/something-ast",
    "crates/something-frontend-tokenizer",
    "crates/something-typechecker",
    "crates/something-slib",
    "crates/something-util"
]
