[package]
name = "parmesan-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casey = "0.4.0"
parmesan-dev-macros = {path="../parmesan-dev-macros"}
parmesan-common = {path="../parmesan-common"}