[package]
name = "parm-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casey = "0.4.0"
parm-dev-macros = {path="../parm-dev-macros"}
parm-common = {path="../parm-common"}